=== AliciaSJF/Desarrollo-Web-Entorno-Cliente/1ºCURSO/expresiones regulares/1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="root-element">
        <xs:complexType>
            <xs:sequence>   
                <xs:element name="a" type="a"/>
                <xs:element name="b" type="b"/>
                <xs:element name="c" type="c"/>
                <xs:element name="d" type="d"/>
                <xs:element name="e" type="e"/>
                <xs:element name="f" type="f"/>
                <xs:element name="g" type="g"/>
                <xs:element name="h" type="h"/>
                <xs:element name="i" type="i"/>
                <xs:element name="j" type="j"/>
                <xs:element name="k" type="k"/>
                <xs:element name="l" type="l"/>
            </xs:sequence>
        </xs:complexType>   
    </xs:element>

    <xs:simpleType name="a">
        <xs:restriction base ="xs:string">
            <xs:pattern value="[A-z]+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="b">
        <xs:restriction base ="xs:string">
            <xs:pattern value="[0-9]{8}[A-z]"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="c">
        <xs:restriction base ="xs:string">
            <xs:pattern value="[0-9]{8}[^a-zIOU\W]"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="d">
        <xs:restriction base ="xs:string">
            <xs:pattern value="[+]?[0-9]{9,12}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="e">
        <xs:restriction base ="xs:string">
            <xs:pattern value="([A-z]|[0-9]){1,16}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="f">
        <xs:restriction base ="xs:string">
            <xs:pattern value="[A-Z]{2}[a-z]{3}[0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="g">
        <xs:restriction base ="xs:string">
            <xs:pattern value="[A-ZÑ][a-zñáéíóú]+[,][ ][A-ZÑ][a-zñáéíóú]+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="h">
        <xs:restriction base ="xs:string">
            <xs:pattern value="[A-z]*[a-z]*[A-z]*[a-z]*[A-z]"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="i">
        <xs:restriction base ="xs:string">
            <xs:pattern value="[0-3][0-9]/[0-1][0-9]/[0-2]-[0-9][0-9][0-9][0-9]"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="j">
        <xs:restriction base ="xs:string">
            <xs:pattern value=""/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="k">
        <xs:restriction base ="xs:string">
            <xs:pattern value=""/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="l">
        <xs:restriction base ="xs:string">
            <xs:pattern value=""/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== AliciaSJF/Desarrollo-Web-Entorno-Cliente/1ºCURSO/expresiones regulares/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<root-element xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="1.xsd">
    <a>A</a>
    <b>12345678A</b>
    <c>12345689P</c>
    <d>+123456789</d>
    <e>a21321</e>
    <f>ASabc123</f>
    <g>Alicia, Sanju</g>
    <h>adsadAdaDAasd</h>
    <i>01/07/2003</i>
    <j></j>
    <k></k>
    <l></l>
</root-element>
